basic info:
  enviroment: 0f
  inactivelimit: 300
  intro: false
  lang: EN
  music: enable
  musiclist: ''
  musicnumber: 0
game settings:
  computer_power: 0.5
  goal_score: 2000
neko settings:
  server: nekos.best
user history:
waifu settings:
  category: waifu
  type: sfw
