basic info:
  environmentA: 0
  environmentB: f
  inactivelimit: 300
  intro: false
  music: enable
  musiclist: ''
  musicnumber: 0
  translate: ''
game settings:
  computer_power: 0.5
  goal_score: 2000
  offline_game: false
neko settings:
  server: nekos.best
user history:
waifu settings:
  category: waifu
  type: sfw
